### PR TITLE
Features : Added RabbitMQ Message Broker Plugin

### PR DESCRIPTION
**Pull request by melsonic**
This plugin lets a user use the functionality of the RabbitMQ message broker system.
/claim #6

### CODE REVIEW

**Comment by melsonic** [comment]
@ashu17706 @ashutoshmindgrep can you check this PR?

**Comment by melsonic** [comment]
any update @ashutoshmindgrep ?

**Comment by siddarthvader** [comment]
@melsonic can we add test cases?

**Comment by siddarthvader** [comment]
LGTM otherwise.

> @melsonic can we add test cases?

**Review by siddarthvader — APPROVED** [review]

**Comment by pavan-godspeed** [comment]
Hello @melsonic, you implemented RabbitMQ as an Eventsource plugin, but could you implement it as a Datasource-as-eventsource plugin, similar to [Kafka](https://github.com/godspeedsystems/gs-plugins/blob/main/plugins/kafka-as-datasource-as-eventsource/src/index.ts)?

**Comment by melsonic** [comment]
> Hello @melsonic, you implemented RabbitMQ as an Eventsource plugin, but could you implement it as a Datasource-as-eventsource plugin, similar to [Kafka](https://github.com/godspeedsystems/gs-plugins/blob/main/plugins/kafka-as-datasource-as-eventsource/src/index.ts)?

Sure, I will incorporate the changes in the next commit :+1:

**Comment by kushal-godspeed** [comment]
@melsonic Thank you for your pull request. While I appreciate your efforts, after careful review, we've decided not to merge this particular PR. Your contributions are valued. If you have any questions or need guidance, feel free to reach out. Thank you for your understanding and continued collaboration.

**Pull request closed without merging**
